/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assesmentcovid;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormCovid extends javax.swing.JFrame {

    /**
     * Creates new form FormCovid
     */
    public FormCovid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sakit = new javax.swing.ButtonGroup();
        Sesak = new javax.swing.ButtonGroup();
        Berkunjung = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        inputsuhu = new javax.swing.JTextField();
        JawabanProses = new javax.swing.JTextField();
        sakitTidak = new javax.swing.JRadioButton();
        sakitYa = new javax.swing.JRadioButton();
        sesakYa = new javax.swing.JRadioButton();
        sesakTidak = new javax.swing.JRadioButton();
        berkunjungYa = new javax.swing.JRadioButton();
        berkunjungTidak = new javax.swing.JRadioButton();
        ulang = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("SELF ASSESMENT COVID-19");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Berapa suhu tubuh anda sekarang?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Apakah anda merasa sakit tenggorokan/ batuk/ pilek/ flu ?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Apakah anda merasa sesak nafas ?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Apakah pernah berkunjung ke daerah Covid dalam 14 hari terakhir?");

        Proses.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Proses.setText("PROSES");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        inputsuhu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputsuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsuhuActionPerformed(evt);
            }
        });

        JawabanProses.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        Sakit.add(sakitTidak);
        sakitTidak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sakitTidak.setText("TIDAK");

        Sakit.add(sakitYa);
        sakitYa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sakitYa.setText("YA");
        sakitYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakitYaActionPerformed(evt);
            }
        });

        Sesak.add(sesakYa);
        sesakYa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sesakYa.setText("YA");

        Sesak.add(sesakTidak);
        sesakTidak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sesakTidak.setText("TIDAK");

        Berkunjung.add(berkunjungYa);
        berkunjungYa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        berkunjungYa.setText("YA");

        Berkunjung.add(berkunjungTidak);
        berkunjungTidak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        berkunjungTidak.setText("TIDAK");

        ulang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ulang.setText("ULANG");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });

        selesai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("*Celcius");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Status Kesehatan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JawabanProses, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(berkunjungYa)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sesakTidak)
                                        .addComponent(sakitTidak))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(berkunjungTidak)))
                                .addGap(123, 123, 123))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Proses, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ulang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sakitYa)
                            .addComponent(sesakYa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sakitTidak)
                    .addComponent(sakitYa))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sesakYa)
                    .addComponent(sesakTidak))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berkunjungYa)
                    .addComponent(berkunjungTidak))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ulang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Proses, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JawabanProses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputsuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputsuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputsuhuActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
    float suhu = Float.parseFloat(inputsuhu.getText());
    String Sakit= "", Sesak="", Berkunjung="";
    int a=0, b=0, c=0, d, e=0;

    if (suhu >= 37.5){
        if (sakitYa.isSelected() && berkunjungYa.isSelected() && sesakYa.isSelected()){
            JawabanProses.setText("anda sakit serius, hubungi Covid Center");
            a++;b++;c++;e++;
        } else if (sakitYa.isSelected()&& sesakYa.isSelected()&&berkunjungTidak.isSelected()){
            JawabanProses.setText ("anda sakit, segera ke dokter");
            a++;b++;e++;
        } else if (sakitYa.isSelected() || sesakYa.isSelected() || berkunjungYa.isSelected()){
            JawabanProses.setText ("anda sakit, segera ke dokter");
            a++;e++;
        } else {
            JawabanProses.setText("istirahat dulu dirumah ya.....");
        }
    } else if (suhu < 37.5){
        if (sakitYa.isSelected() && berkunjungYa.isSelected() && sesakYa.isSelected()){
            JawabanProses.setText ("anda sakit serius, hubungi Covid Center");
            a++; b++; c++;
        } else if (sakitYa.isSelected() || sesakYa.isSelected()&&berkunjungYa.isSelected()){
            JawabanProses.setText("anda sakit, segera ke dokter");
            a++;b++;
        } else if (sakitYa.isSelected()||sesakYa.isSelected()&& berkunjungYa.isSelected()){
            JawabanProses.setText("anda sakit, segera ke dokter");
            a++;
        } else if(sakitTidak.isSelected()&& sesakTidak.isSelected() && berkunjungYa.isSelected()){
            JawabanProses.setText("observasi di rumah dulu 14 hari ya...");
            c++;
        } else {
            JawabanProses.setText("anda sehat");
        }
    }   
    String pesan="";
    d=a+b+c+e;
    if (d>3) {
            JOptionPane.showMessageDialog(null, "BAHAYA COVID SANGAT TINGGI");
          

        } else if (d<=3 && d>2){          
            JOptionPane.showMessageDialog(null, "BAHAYA COVID TINGGI");
        }else if (d<=2 && d!=0){
           JOptionPane.showMessageDialog(null, "BAHAYA COVID SEDANG");
        }else{
            JOptionPane.showMessageDialog(null, "BAHAYA COVID RENDAH");
        }
    }//GEN-LAST:event_ProsesActionPerformed

    private void sakitYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakitYaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sakitYaActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        // TODO add your handling code here:
        inputsuhu.setText("");
        JawabanProses.setText("");
       
        
    }//GEN-LAST:event_ulangActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCovid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Berkunjung;
    private javax.swing.JTextField JawabanProses;
    private javax.swing.JButton Proses;
    private javax.swing.ButtonGroup Sakit;
    private javax.swing.ButtonGroup Sesak;
    private javax.swing.JRadioButton berkunjungTidak;
    private javax.swing.JRadioButton berkunjungYa;
    private javax.swing.JTextField inputsuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton sakitTidak;
    private javax.swing.JRadioButton sakitYa;
    private javax.swing.JButton selesai;
    private javax.swing.JRadioButton sesakTidak;
    private javax.swing.JRadioButton sesakYa;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
